[project]
name = "player-count-by-bs-version"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "packaging>=25.0",
    "requests>=2.32.5",
    "tqdm>=4.67.1",
]
