name: uv Run

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  build-and-release:
    name: uv
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v6.5.0
    
    - name: Set up Python
      run: uv python install

    - name: Install modules
      run: uv sync --all-extras --dev
    
    - name: Run uv
      run: uv run main.py

    - name: Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v6
      with:
        commit_message: Auto Commit